spring:
  application:
    name: perquizz
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: local_user
    password: local_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5