db:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  name: ${POSTGRES_DB:local_db}
  user: ${POSTGRES_USER:local_user}
  password: ${POSTGRES_PASSWORD:local_password}

spring:
  application:
    name: perquizz
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    jpa:
      hibernate:
        ddl-auto: none

jwt:
  config:
    seconds-to-expire: 3600
    password-key: ${JWT_PASSWORD:testkey}
