db:
  host: localhost
  port: 5432
  name: local_db
  user: local_user
  password: local_password

spring:
  application:
    name: perquizz
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5