name: Automated Tests

on: pull_request
jobs:
    junit:
        name: Junit Ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                java-version: 17
                distribution: 'temurin'

            - name: Execute tests
              run: ./gradlew test
